sonar.projectKey=ncs_ncs_18441223-348a-4735-9aed-04590952c3ae
sonar.sources=src/lucid
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true